export const fakeData = [
    {
        id: '5f56e5cd43afa706471f4906',
        picture:
            'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTAOF7VTeJ4H8mvqFpEt1fiRLXdNIVKZIgAaA&usqp=CAU',
        experience: 8,
        name: 'Lindsay Knowles',
        gender: 'female',
        company: 'FROSNEX',
        email: 'lindsayknowles@frosnex.com',
        price: 857,
        phone: '+1 (968) 543-3904',
        address: '792 Harkness Avenue, Cobbtown, Texas, 27',
        course: 'Spoken-English',
        description:
            "This is the best course about this topic. and i so busy to making logical part of the website so i didn't have time to write the deschiption :) ",
    },
    {
        id: '5f56e5cd3a2f0e8ea940bf71',
        picture:
            'https://www.freecodecamp.org/news/content/images/2020/04/screely-1586183781361.png',
        experience: 11,
        name: 'Lea Gould',
        gender: 'female',
        company: 'MEDCOM',
        email: 'leagould@medcom.com',
        price: 939,
        phone: '+1 (801) 445-3049',
        address: '981 Seacoast Terrace, Barclay, Wyoming, 69',
        course: 'Website-development',
        description:
            "This is the best course about this topic. and i so busy to making logical part of the website so i didn't have time to write the deschiption :) ",
    },
    {
        id: '5f56e5cde6d78cd56e50a057',
        picture:
            'https://d2x3xhvgiqkx42.cloudfront.net/12345678-1234-1234-1234-1234567890ab/07611794-742f-4d53-8c5b-24ba712a6934/2018/05/27/54bec495-5848-42a5-ae3e-7fb9887b00d0.png',
        experience: 13,
        name: 'Shelley Chaney',
        gender: 'female',
        company: 'RAMEON',
        email: 'shelleychaney@rameon.com',
        price: 610,
        phone: '+1 (977) 466-2367',
        address: '332 Stillwell Place, Terlingua, Palau, 11',
        course: 'Wix theme development',
        description:
            "This is the best course about this topic. and i so busy to making logical part of the website so i didn't have time to write the deschiption :) ",
    },
    {
        id: '5f56e5cd6643d6c67f50ca56',
        picture:
            'https://kinsta.com/wp-content/uploads/2017/12/wordpress-admin.png',
        experience: 11,
        name: 'Cooper Gamble',
        gender: 'male',
        company: 'ORBALIX',
        email: 'coopergamble@orbalix.com',
        price: 432,
        phone: '+1 (865) 412-2528',
        address: '164 Ridgewood Avenue, Woodlands, Maine, 54',
        course: 'WordPress',
        description:
            "This is the best course about this topic. and i so busy to making logical part of the website so i didn't have time to write the deschiption :) ",
    },
    {
        id: '5f56e5cd94406d9fbc21007a',
        picture:
            'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRQH71lpZf1Irwwir52pdh4b2J_CmiqWblhaw&usqp=CAU',
        experience: 10,
        name: 'Gutierrez Jacobs',
        gender: 'male',
        company: 'CORPULSE',
        email: 'gutierrezjacobs@corpulse.com',
        price: 628,
        phone: '+1 (804) 586-2127',
        address: '167 Poly Place, Motley, Guam, 65',
        course: 'Css-Advanced',
        description:
            "This is the best course about this topic. and i so busy to making logical part of the website so i didn't have time to write the deschiption :) ",
    },
    {
        id: '5f56e5cd7adb912547a22d28',
        picture:
            'https://w3-lab.com/wp-content/uploads/2019/12/Get-the-Most-Fancied-Web-Development-Services-min-scaled.jpg',
        experience: 13,
        name: 'Dillon Wells',
        gender: 'male',
        company: 'GEEKNET',
        email: 'dillonwells@geeknet.com',
        price: 828,
        phone: '+1 (977) 589-3577',
        address: '758 Cortelyou Road, Bainbridge, Hawaii, 73',
        course: 'Web-design',
        description:
            "This is the best course about this topic. and i so busy to making logical part of the website so i didn't have time to write the deschiption :) ",
    },
    {
        id: '5f56e5cd17cb94cadadd35ad',
        picture:
            'https://cdn.educba.com/academy/wp-content/uploads/2018/12/Is-MongoDB-NoSQL.jpg',
        experience: 10,
        name: 'Cross Howe',
        gender: 'male',
        company: 'ZEPITOPE',
        email: 'crosshowe@zepitope.com',
        price: 796,
        phone: '+1 (804) 579-3468',
        address: '926 Columbus Place, Colton, Oregon, 37',
        course: 'MongoDb-Mongoes',
        description:
            "This is the best course about this topic. and i so busy to making logical part of the website so i didn't have time to write the deschiption :) ",
    },
    {
        id: '5f56e5cdea05eaf0b025e651',
        picture:
            'https://miro.medium.com/max/6668/1*XP-mZOrIqX7OsFInN2ngRQ.png',
        experience: 6,
        name: 'Gibbs Rowland',
        gender: 'male',
        company: 'GALLAXIA',
        email: 'gibbsrowland@gallaxia.com',
        price: 223,
        phone: '+1 (894) 402-3332',
        address: '429 Richards Street, Soudan, Illinois, 36',
        course: 'Express Js',
        description:
            "This is the best course about this topic. and i so busy to making logical part of the website so i didn't have time to write the deschiption :) ",
    },
    {
        id: '5f56e5cd14c423ceab5edcc3',
        picture:
            'https://image.slidesharecdn.com/git-170223190754/95/introduction-to-git-and-github-1-638.jpg?cb=1487876917',
        experience: 6,
        name: 'Mayra Chen',
        gender: 'female',
        company: 'MYOPIUM',
        email: 'mayrachen@myopium.com',
        price: 759,
        phone: '+1 (884) 476-2331',
        address: '255 Navy Street, Coultervillle, Mississippi, 25',
        course: 'Git-Github',
        description:
            "This is the best course about this topic. and i so busy to making logical part of the website so i didn't have time to write the deschiption :) ",
    },
    {
        id: '5f56e5cd6c1368c2d272736d',
        picture:
            'https://bs-uploads.toptal.io/blackfish-uploads/blog/post/seo/og_image_file/og_image/15921/secure-rest-api-in-nodejs-18f43b3033c239da5d2525cfd9fdc98f.png',
        experience: 13,
        name: 'Pacheco Huff',
        gender: 'male',
        company: 'WAZZU',
        email: 'pachecohuff@wazzu.com',
        price: 215,
        phone: '+1 (929) 430-2816',
        address: '802 Clark Street, Finderne, Rhode Island, 94',
        course: 'Node-Api',
        description:
            "This is the best course about this topic. and i so busy to making logical part of the website so i didn't have time to write the deschiption :) ",
    },
    {
        id: '5f56e5cdb0da3c882cf03ef7',
        picture:
            'https://miro.medium.com/max/675/1*dqLV7KjUtg57JPBCilqxSQ.jpeg',
        experience: 8,
        name: 'Munoz Brennan',
        gender: 'male',
        company: 'AUTOGRATE',
        email: 'munozbrennan@autograte.com',
        price: 907,
        phone: '+1 (888) 429-2440',
        address: '770 Wythe Place, Belmont, Utah, 89',
        course: 'HTML-CSS',
        description:
            "This is the best course about this topic. and i so busy to making logical part of the website so i didn't have time to write the deschiption :) ",
    },
    {
        id: '5f56e5cdea8ee9a3902b9573',
        picture:
            'https://letusdebug.com/wp-content/uploads/2019/11/javascript_image.jpg',
        experience: 14,
        name: 'Annmarie Ross',
        gender: 'female',
        company: 'GEOLOGIX',
        email: 'annmarieross@geologix.com',
        price: 479,
        phone: '+1 (917) 582-3159',
        address: '315 Kent Avenue, Genoa, Northern Mariana Islands, 20',
        course: 'Javascript-everything',
        description:
            "This is the best course about this topic. and i so busy to making logical part of the website so i didn't have time to write the deschiption :) ",
    },
    {
        id: '5f56e5cdc3b475a57acb7019',
        picture: 'https://i.morioh.com/200623/6c839150.jpg',
        experience: 6,
        name: 'Alisha Stark',
        gender: 'female',
        company: 'ZILLANET',
        email: 'alishastark@zillanet.com',
        price: 772,
        phone: '+1 (912) 414-3758',
        address: '457 Varet Street, Woodlake, Michigan, 59',
        course: 'React',
        description:
            "This is the best course about this topic. and i so busy to making logical part of the website so i didn't have time to write the deschiption :) ",
    },
    {
        id: '5f56e5cd0ce5e1ec2aba782a',
        picture:
            'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQQttnTl46_jO5MnbQSap4zxucJ6ncC1ryulA&usqp=CAU',
        experience: 12,
        name: 'Wall Berger',
        gender: 'male',
        company: 'CHILLIUM',
        email: 'wallberger@chillium.com',
        price: 815,
        phone: '+1 (951) 565-2827',
        address: '426 Canal Avenue, Trinway, Arizona, 30',
        course: 'React-Redux',
        description:
            "This is the best course about this topic. and i so busy to making logical part of the website so i didn't have time to write the deschiption :) ",
    },
    {
        id: '5f56e5cd5d1b08ced0e900f1',
        picture:
            'https://www.futuremind.com/m/cache/c8/15/c8150d863e584ed42ccfbdc3f3f1aa3a.jpg',
        experience: 9,
        name: 'Freda Holden',
        gender: 'female',
        company: 'APPLIDECK',
        email: 'fredaholden@applideck.com',
        price: 859,
        phone: '+1 (841) 462-2519',
        address: '415 Emerald Street, Oley, Wisconsin, 68',
        course: 'React-Native',
        description:
            "This is the best course about this topic. and i so busy to making logical part of the website so i didn't have time to write the deschiption :) ",
    },
];
